# Generated by Django 2.1.2 on 2019-02-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20190214_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='text',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
