# Generated by Django 2.1.2 on 2019-02-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20190214_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ques',
            name='slug',
        ),
        migrations.AlterField(
            model_name='ques',
            name='ocrtext',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='ques',
            name='title',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
