# Generated by Django 2.1.2 on 2019-02-15 03:40

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20190214_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='corrected',
            field=models.BooleanField(default=False, verbose_name='Approve'),
        ),
        migrations.AddField(
            model_name='ques',
            name='corrected_date',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ques',
            name='verify',
            field=models.BooleanField(default=False, verbose_name='Approve'),
        ),
        migrations.AddField(
            model_name='ques',
            name='verify_date',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
    ]
