# Generated by Django 2.1.2 on 2019-02-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20190215_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='corrected',
            field=models.BooleanField(default=False, verbose_name='corrected'),
        ),
        migrations.AlterField(
            model_name='ques',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ques',
            name='verify',
            field=models.BooleanField(default=False, verbose_name='verify'),
        ),
    ]
