# Generated by Django 2.1.2 on 2019-02-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20190215_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='ocrtext',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='ques',
            name='text',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
